name: firebase_standard_utilities
description: #Description for this branch package
version: 0.0.1
homepage: #WebPage

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.0

